### ISSUE TITLE
Requires a couple extra steps on Debian: Node and fsevents@0.3.8 

### ISSUE THREAD

**Issue by pachpict** [mohayonao/seurat#5]
Installing this on Linux Mint 18 (deb-based), I needed to do the following, which may be useful to add to the readme:

`sudo npm install --no-optional -g seurat`

(Note --no-optional)

.. and to avoid ...

`/usr/bin/env: ‘node’: No such file or directory`

Install the following...

`sudo apt-get install nodejs-legacy`

**Comment by Qix-** [comment]
@pachpict don't install node from Aptitude. It's _consistently_ out of date and still installs to `/usr/local/bin/nodejs` instead of `node`. Alternative, if you insist on using Aptitude, instead run

```
ln -s "$(which nodejs)" "$(dirname "$(which nodejs)")/node"
```

Why do you need to use `--no-optional`? Optional dependencies that fail should be ignored by npm.

Btw, most of this has nothing to do with Seurat specifically.

**Comment by pachpict** [comment]
Thanks for the correction Qix. I'll close the issue.
